server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        - id: deposit-funds
          uri: http://localhost:5000
          predicates:
            - Path=/api/v1/depositFunds/**
        - id: withdraw-funds
          uri: http://localhost:5000
          predicates:
            - Path=/api/v1/withdrawFunds/**
        - id: account-cmd
          uri: http://localhost:5000
          predicates:
            - Path=/api/v1/openBankAccount/**
        - id: account-cmd-close
          uri: http://localhost:5000
          predicates:
            - Path=/api/vi/closeBankAccount/**
        - id: account-query
          uri: http://localhost:5002
          predicates:
            - Path=/api/v1/query/**
        - id: bank-records
          uri: http://localhost:5003
          predicates:
            - Path=/api/v1/bankRecords/**
        - id: auth-register
          uri: https://localhost:7274
          predicates:
            - Path=/api/auth/register
          metadata:
            response-timeout: 10000
          filters:
            - name: SecureHeaders
          ssl:
            useInsecureTrustManager: true