apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-query
  template:
    metadata:
      labels:
        app: account-query
    spec:
      containers:
        - name: account-query
          image: account-query:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
---
apiVersion: v1
kind: Service
metadata:
  name: account-query
spec:
  selector:
    app: account-query
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
