server:
  port: 5000

spring:
  data:
    mongodb:
      host: mongo-container
      port: 27017
      database: bankAccount
  kafka:
    producer:
      bootstrap-servers: docker-kafka-1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer