spring:
  profiles:
    active: k8s

  kafka:
    bootstrap-servers: host.docker.internal:9092
    consumer:
      group-id: topic-logger-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
            type:
              mapping: |
                com.techbank.account.common.events.AccountClosedEvent:com.bankrecords.records.Events.AccountClosedEvent,
                com.techbank.account.common.events.AccountOpenedEvent:com.bankrecords.records.Events.AccountOpenedEvent,
                com.techbank.account.common.events.FundsDepositedEvent:com.bankrecords.records.Events.FundsDepositedEvent,
                com.techbank.account.common.events.FundsWithdrawnEvent:com.bankrecords.records.Events.FundsWithdrawnEvent
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      database: bankRecords
server:
  port: 8082